### ISSUE TITLE
"flatc not installed. Using pre-generated flatbuffers." should be an error, not a warning

### ISSUE THREAD

**Issue by yurivict** [akb825/ModularShaderLanguage#5]
flatbuffers now has static assert that prevents the use of headers generated by other versions of flatbuffers.
This makes using pre-generated headers error-prone and they should be avoided altogether.

**Comment by akb825** [comment]
The flatbuffer headers for the pre-generated flatbuffers are checked in under Shared/external/flatbuffers. The one potential situation where this can break is if you have the flatbuffers headers installed but not flatc. I can see about adding a check to ensure that it will always use the embedded headers if flatc isn't installed.

**Comment by yurivict** [comment]
They now recommend to always regenerate headers during build.

**Comment by akb825** [comment]
As a *recommendation* I completely agree. If you change a flatbuffer schema, you want the headers to be regenerated automatically without a manual secondary build step, as well as avoid any incompatibilities with the core flatbuffer headers.

As a *requirement* this only makes sense if you intend to modify the flatbuffer schema. A standard user of the library and/or tool has no need to modify the schema, and it very rarely changes. Any added dependency makes the project harder to build, especially on systems like Windows or a default Mac install (if you don't have something like homebrew set up), so when it's possible to build with pre-generated headers it's very convenient.

That said, that situations such as the headers are found but flatc not breaking the build was an oversight. I'll push up a fix to make this more robust (as well as fix the other issues you reported) tomorrow.
