### ISSUE TITLE
Congigure fails when MSL_SHARED=ON and SPIRV_TOOLS_BUILD_STATIC=OFF

### ISSUE THREAD

**Issue by yurivict** [akb825/ModularShaderLanguage#6]
```
CMake Error: install(EXPORT "MSLCompileTargets" ...) includes target "msl_compile" which requires target "SPIRV-Tools-opt" that is not in any export set.
CMake Error in Compile/CMakeLists.txt:
  export called with target "msl_compile" which requires target
  "SPIRV-Tools-opt" that is not in any export set.
```

Version: 1.5.1

**Comment by akb825** [comment]
I fixed this with the latest revision. In case you were setting `SPIRV_TOOLS_BUILD_STATIC=OFF` manually to ensure the full package is installed with shared libraries, the SPIRV-Tools libraries I use are statically linked with libmsl_compile.so and not exposed externally to the library. The static SPIRV-Tools libraries also aren't a part of the install package.
